version: '3'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0.31
    environment:
      MYSQL_USER: 'dev'  
      MYSQL_PASS: 'dev'
      MYSQL_ROOT_PASSWORD: 'root' 
    ports:
      - "3306:3306"
    volumes:
      -  ./mysql_data:/var/lib/mysql
